### ISSUE TITLE
BTC-Client Docker Container Continuously Restarting 

### ISSUE THREAD

**Issue by jjacks95** [graphsense/btc-client#1]
Hi,

I have been trying to install GraphSense but have come across an issue where I am able to build the container and start it with bitcoin data, but then the docker container continuously restarts making it impossible to attach.

Any idea why this might be occurring?

I should add docker logs show:
```
Error: Cannot write to data directory '/opt/graphsense/data/'; check permissions.
```
I checked permissions the folders are set and owned by `dockeruser`
Which I had to do manually but the error still exists.

**Comment by defconst** [comment]
Are the UIDs the same (inside the docker container and on the host system)? it should be 10000, you can check with the `id` command.

**Comment by jjacks95** [comment]
@defconst  Sorry about the slow response, thanks for getting back to me.

Not able to check inside the docker container as you can't attach it.

But I did move forward to graphsense blocksci and was able to access that container and the UIDs are not the same `containerUser = 10000` & `dockeruser = 1006`

Could this be the cause? Any idea how to fix it?

**Comment by defconst** [comment]
Yes, this could be the cause. Two possibilities to fix it:

- change the UID to form 10000 to 1006 in the Dockerfile, or
- change the UID on the host system from 1006 to 10000 (`usermod -u 10000 dockeruser` or edit `/etc/passwd`)

**Comment by jjacks95** [comment]
@defconst ok thanks for all the help. Will try these changes and let you know.
