### ISSUE TITLE
Docker compose file for currency clients

### ISSUE THREAD

**Issue by behas** [graphsense/btc-client#2]
Provide a docker-compose file for bootstrapping all clients

**Comment by MrNonoss** [comment]
Indeed,

It would be a great enhancement ^^

**Comment by behas** [comment]
@defconst what about creating a repository "crypto-clients", with a single docker-compose and README file and git submodule links to all the clients.

As a bonus, for quick bootstrapping, we could also provide a pre-synced blockchain dumps per currency; this should be optional.

**Comment by behas** [comment]
@defconst this can be closed, right?

**Comment by MrNonoss** [comment]
Thank you for your good work on this point !

**Comment by behas** [comment]
Btw. what about creating a repo "clients", which links all clients as git submodules and provides a single docker compose file for all clients? This would facilitate setting up the entire thing. As a plus we could even provide pre-synced chains for download somewhere. @defconst your opinion in this?

**Comment by defconst** [comment]
Added https://github.com/graphsense/graphsense-setup/commit/e45327bff5d2c65a3ca08ccad6540b2d774eaa0e
