### ISSUE TITLE
Permission error in ownership of datadir

### ISSUE THREAD

**Issue by falcorocks** [graphsense/btc-client#3]
Hi,
there is a problem in your docker file.
The container will restart continuously.

```
$ docker logs bitcoin:

************************
EXCEPTION: N5boost10filesystem16filesystem_errorE
boost::filesystem::create_directory: Permission denied: "/opt/graphsense/data/blocks"
bitcoin in AppInit()
```

To fix it is sufficient to add the -R flag in the chown command in the Docker file (line 7):
`chown -R dockeruser /opt/graphsense`

I'll submit a pull request for this issue

**Comment by falcorocks** [comment]
same thing in graphsense/bch-client...

**Comment by defconst** [comment]
Permissions are set in `docker/start.sh`
