### ISSUE TITLE
Git clone doesn't work well

### ISSUE THREAD

**Issue by rubujubi** [graphsense/btc-client#6]
in docker/makefile:
```
install:
	git clone https://github.com/bitcoin/bitcoin.git src && \
	cd src && \
	git checkout tags/v0.20.0 -b local && \
	./autogen.sh && \
	./configure --without-gui --disable-zmq --disable-upnp-default --disable-tests --disable-wallet && \
	make install
```
`git clone` is not resumable, it takes a long time to clone and the connection might break in the middle of the process, when this happens I need to start again and it might break again...

As I can see from the code above, only v0.20.0 is used, so can this be modified to `git clone -b 0.20 https://github.com/bitcoin/bitcoin.git`, or can the bitcoin repo be packed together with this btc-client, so it can be a lot easier to prepare the whole environment?

**Comment by defconst** [comment]
Thanks for the suggestion. Shallow clone with `--depth=1` now used in `develop` branch.
